### PR TITLE
Use smooth scrolling for chatbox

### PR DESCRIPTION
**Pull request by Excellify**
Implements smooth scroll for the chat box, the duration can be configured

### CODE REVIEW

**Comment by AnatoleAM** [comment]
This is gonna need to hook into settings and be default-off. Smooth-scrolling chat as a default would be controversial

**Comment by AnatoleAM** [comment]
Should rebase this & add a config option for it. Then it's fine

**Comment by Excellify** [comment]
Should be ready for merge

**Review by AnatoleAM — APPROVED** [review]
LGTM

**Pull request merged**
